# Algebra Linear

A álgebra linear é uma ferramenta muito importante na física.
Ela é um ramo da matemática que surgiu do estudo  de sistemas de equações lineares (algébricas ou diferenciais), utiliza alguns conceitos e estruturas fundamentais da matemática como vetores, espaços vetoriais, transformações lineares, sistemas de equações lineares e matrizes.

Uma documentação muito usada é: https://numpy.org/doc/stable/reference/routines.linalg.html

In [1]:
# Bibliotecas
import numpy as np

### Vetor

Podemos definir um vetor de diferentes maneiras.

In [2]:
# usando array, definição explicita
x = np.array([0, 1, 2, 3, 4, 5])

# usando arange (inicio, final não incluido, passo)
y = np.arange(0, 6, 1)

# usando linspace (inicio, final incluido, número de elementos)
z = np.linspace(0, 5, 6)

print('x =', x)
print('y =', y)
print('z =', z)

x = [0 1 2 3 4 5]
y = [0 1 2 3 4 5]
z = [0. 1. 2. 3. 4. 5.]


### Matriz

In [3]:
# definição explicita

m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

m2 = np.matrix('1 2 3; 4 5 6; 7 8 9')

print('m1 =',m1)
print('m2 =',m2)

m1 = [[1 2 3]
 [4 5 6]
 [7 8 9]]
m2 = [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Matriz NxN com 1 em todas k-th diagonais
np.eye(N=4, k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
# matriz preenchida de 1
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
# matriz preenchida de 0
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Transposta, Inversa e Determinante

In [7]:
A = np.array([[0, 1], 
              [1, 0]])

print('Transposta de A: \n', np.transpose(A))

print('Inversa de A: \n', np.linalg.inv(A))

print('Determinante de A: \n', np.linalg.det(A))


Transposta de A: 
 [[0 1]
 [1 0]]
Inversa de A: 
 [[0. 1.]
 [1. 0.]]
Determinante de A: 
 -1.0


### Produto Escalar e Produto Vetorial

In [8]:
x = np.array([1, 0, 0])
y = np.array([0, 1, 0])

PE = np.dot(x, y)
print('Produto Escalar:', PE)

PV = np.cross(x, y)
print('Produto Vetorial:', PV)

Produto Escalar: 0
Produto Vetorial: [0 0 1]


### Produto de Matrizes

In [9]:
# let's use simple 2x2 matrices
A = np.array([[0, 1], [1, 0]])
B = np.array([[1, 2], [3, 4]])

print('O produto das matrizes A e B é: \n', np.dot(A, B))

print('ou também: \n', A @ B)

print('Multiplicação elemento por elemento das matrizes A e B é \n', A*B)

O produto das matrizes A e B é: 
 [[3 4]
 [1 2]]
ou também: 
 [[3 4]
 [1 2]]
Multiplicação elemento por elemento das matrizes A e B é 
 [[0 2]
 [3 0]]


### Autovalores e Autovetores 

In [10]:
A = np.array([[0, 1], [1, 0]])

# usando eigvalsh, usado quando a matriz é hermitiana
evals = np.linalg.eigvalsh(A)
print('Autovalores da matriz hermitiana:', evals)

evals1 = np.linalg.eigvals(A)
print('Autovalores de qualquer matriz:', evals1)


# calculando autovetores e autovalores ao mesmo tempo
evals, evecs = np.linalg.eigh(A)
print('Autovalores:',evals)
print('Primeiro autovetor:', evecs[:,0])
print('Primeiro autovetor:', evecs[:,1])

Autovalores da matriz hermitiana: [-1.  1.]
Autovalores de qualquer matriz: [ 1. -1.]
Autovalores: [-1.  1.]
Primeiro autovetor: [-0.70710678  0.70710678]
Primeiro autovetor: [0.70710678 0.70710678]


### Sistema de equações lineares

Seja por exemplo o sistema:

$4x_0+x_1=4$

$2x_1+x_0=8$

ou seja,

$\begin{pmatrix}
4 & 1\\
1 & 2 
\end{pmatrix}
\begin{pmatrix}
x_0 \\
x_1 
\end{pmatrix}
=
\begin{pmatrix}
4 \\
8 
\end{pmatrix}$


In [11]:
A = np.array([[4, 1], [1, 2]])
B = np.array([4, 8])

X = np.linalg.solve(A, B)
print('Solução:', X)

# ou 
X = np.linalg.inv(A) @ B
print('Ou:', X)

Solução: [0. 4.]
Ou: [0. 4.]
